[workspace]
members = [
    "collections/rust/src/hashmap",
    "collections/rust/src/btreemap",
    "collections/rust/src/heap",
    "collections/rust/src/imrc_hashmap",
    "collections/rust/src/movm",
    "collections/rust/src/movm_dynamic",
    "basic_dao/rust",
    "heartbeat/rust",
    "pub-sub/rust/publisher",
    "pub-sub/rust/subscriber",
]
