[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.10.0"
stableheapbtreemap = "1.3.0"
map = "9.0.0"
splay = "0.1.0"
vector = "0.2.0"
StableBTree = "https://github.com/crusso/MotokoStableBTree#claudio"
