[package]
name = "dip721_nft"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-cdk.workspace = true
candid.workspace = true
serde.workspace = true
utils = { path = "../../../utils/rust" }

[lib]
crate-type = ["cdylib"]
