name: Perf

on:
  push:
    branches: [main]
  pull_request:

jobs:
  perf:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      DFX_VERSION: 0.12.0-beta.1
      VESSEL_VERSION: v0.6.4
      IC_REPL_VERSION: 0.3.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}      
      - name: Install dfx
        run: |
          echo y | DFX_VERSION=$DFX_VERSION bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          wget https://github.com/chenyan2002/ic-repl/releases/download/$IC_REPL_VERSION/ic-repl-linux64
          cp ./ic-repl-linux64 /usr/local/bin/ic-repl
          chmod a+x /usr/local/bin/ic-repl
          wget https://github.com/dfinity/vessel/releases/download/$VESSEL_VERSION/vessel-linux64
          cp ./vessel-linux64 /usr/local/bin/vessel
          chmod a+x /usr/local/bin/vessel
      - name: Start dfx
        run: |
          dfx cache install
          dfx start --background
      - name: collections
        run: |
          pushd collections
          make
          popd
      - name: basic_dao
        run: |
          pushd basic_dao
          make
          popd
      - name: Upload report
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: collections/_out/
          SINGLE_COMMIT: true
