name: Perf

on:
  push:
    branches: [main]
  pull_request:

jobs:
  perf:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      DFX_VERSION: 0.13.1
      VESSEL_VERSION: v0.6.4
      IC_REPL_VERSION: 0.3.17
      MOC_VERSION: 0.8.4
    steps:
      - uses: actions/checkout@v3
      - name: Checkout out gh-pages report
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: main
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-python@v4
        if: github.event_name == 'pull_request'
        with:
          python-version: "3.9"
      - name: Install Python dependencies
        if: github.event_name == 'pull_request'
        run: |
          python -m pip install --upgrade pip
          pip install pandas markdown lxml html5lib bs4 tabulate
      - name: Install dfx
        run: |
          echo y | DFX_VERSION=$DFX_VERSION bash -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
          wget https://github.com/chenyan2002/ic-repl/releases/download/$IC_REPL_VERSION/ic-repl-linux64
          cp ./ic-repl-linux64 /usr/local/bin/ic-repl
          chmod a+x /usr/local/bin/ic-repl
          wget https://github.com/dfinity/vessel/releases/download/$VESSEL_VERSION/vessel-linux64
          cp ./vessel-linux64 /usr/local/bin/vessel
          chmod a+x /usr/local/bin/vessel
          dfx cache install
          cd $(dfx cache show)
          wget https://github.com/dfinity/motoko/releases/download/$MOC_VERSION/motoko-linux64-$MOC_VERSION.tar.gz
          tar zxvf motoko-linux64-$MOC_VERSION.tar.gz
      - name: Start dfx
        run: |
          dfx start --background
      - name: Run perf
        run: make
      - name: Generate table
        if: github.event_name == 'pull_request'
        run: |
          find _out/ -name 'README.md' -exec cat {} \; > TABLE_OLD.md
          cd _out
          find . -name 'README.md' -exec python ../.github/workflows/diff.py {} ../main/{} \; > ../TABLE.md
      - name: Read table
        if: github.event_name == 'pull_request'
        id: perf
        uses: juliangruber/read-file-action@v1
        with:
          path: ./TABLE.md
      - name: Find performance comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2 
        id: fc                            
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- perf comment -->'
      - name: Create or update performance comment
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- perf comment -->
            > **Warning**
            > The flamegraph link only works after you merge.
            ${{ steps.perf.outputs.content }}
          edit-mode: replace
      - name: Upload report
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _out/
          SINGLE_COMMIT: true
